
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author LENOVO
 */
public class BodyAvailable extends javax.swing.JFrame {
       JFrame f;
    /**
     * Creates new form Register
     */
    public BodyAvailable() {
        
        initComponents();
        
        connect();
        Table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    Connection conn;
    Statement stmt;
    PreparedStatement pst;
   
    
    
    public void connect(){
          
        try {  
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/register","root","");
            System.out.println("success in db connection....");
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
     
    }
    
    private void Table_update(){
        int cc;
        try{
            pst = conn.prepareStatement("SELECT * FROM bodydonar");
            ResultSet Rs = pst.executeQuery();
            ResultSetMetaData RSMD = Rs.getMetaData();
            cc = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) jTablebody.getModel();
            DFT.setRowCount(0);
            while(Rs.next()){
                Vector v1 = new Vector();
                
                for(int li=1; li<=cc; li++){
                    v1.add(Rs.getString("id"));
                    v1.add(Rs.getString("first_and_middle_name"));
                    v1.add(Rs.getString("lname"));
                    v1.add(Rs.getString("address"));
                    v1.add(Rs.getString("mobileno"));
                    v1.add(Rs.getString("age"));
                    v1.add(Rs.getString("blood_gp"));
                    
                }
                DFT.addRow(v1);
            }
            
            
            
            
            
        }  catch (SQLException ex) {
               Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
           }
    }
    
     public void search(String str){
       DefaultTableModel DFT = (DefaultTableModel) jTablebody.getModel();
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(DFT);
        jTablebody.setRowSorter(sorter);
        sorter.setRowFilter(RowFilter.regexFilter(str));
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablebody = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        sr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Donner Register");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Body Registered");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 46));

        jTablebody.setAutoCreateRowSorter(true);
        jTablebody.setBackground(new java.awt.Color(0, 255, 204));
        jTablebody.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 1, true));
        jTablebody.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTablebody.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "first_and_middle_name", "lname", "address", "mobileno", "age", "blood_gp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablebody.setGridColor(new java.awt.Color(0, 51, 255));
        jTablebody.setSelectionBackground(new java.awt.Color(0, 0, 255));
        jTablebody.setShowGrid(false);
        jTablebody.setShowHorizontalLines(true);
        jTablebody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablebodyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablebody);
        if (jTablebody.getColumnModel().getColumnCount() > 0) {
            jTablebody.getColumnModel().getColumn(0).setResizable(false);
            jTablebody.getColumnModel().getColumn(1).setResizable(false);
            jTablebody.getColumnModel().getColumn(2).setResizable(false);
            jTablebody.getColumnModel().getColumn(3).setResizable(false);
            jTablebody.getColumnModel().getColumn(4).setResizable(false);
            jTablebody.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 960, 450));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Search:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srActionPerformed(evt);
            }
        });
        sr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srKeyReleased(evt);
            }
        });
        getContentPane().add(sr, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 120, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homebackground.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1490, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTablebodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablebodyMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel model = (DefaultTableModel) jTablebody.getModel();
//        int selectedIndex = jTablebody.getSelectedRow();
//        int id= Integer.parseInt(model.getValueAt(selectedIndex,0).toString());
//        txtfname.setText(model.getValueAt(selectedIndex,1).toString());
//        txtlname.setText(model.getValueAt(selectedIndex,2).toString());
//        txtdob.setText(model.getValueAt(selectedIndex,3).toString());
//        txtcrime.setText(model.getValueAt(selectedIndex,4).toString());
//        txtage.setText(model.getValueAt(selectedIndex,5).toString());

        
        
    }//GEN-LAST:event_jTablebodyMouseClicked

    private void srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srActionPerformed

    private void srKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srKeyReleased
        // TODO add your handling code here:
        String s1 = sr.getText();
        search(s1);
    }//GEN-LAST:event_srKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
//                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablebody;
    private javax.swing.JTextField sr;
    // End of variables declaration//GEN-END:variables
}
